services:
  confluence:
    build: ./confluence
    volumes:
      - confluence-data:/var/atlassian/confluence
      - confluence-logs:/opt/atlassian/confluence/logs
    environment:
      - ATL_JDBC_URL=jdbc:postgresql://db:5432/confluencedb
      - ATL_JDBC_USER=confluence
      - ATL_JDBC_PASSWORD=jellyfish
      - ATL_DB_DRIVER=org.postgresql.Driver
      - ATL_DB_TYPE=postgresql
      - ATL_PROXY_NAME=192.168.xxx.xx
      - ATL_PROXY_PORT=8443
      - ATL_TOMCAT_SCHEME=https
      - ATL_TOMCAT_SECURE=true
      - CATALINA_OPTS=-Dconfluence.jmx.disabled=true -Dspring.jmx.enabled=false -Dcom.sun.management.jmxremote=false -Djavax.management.builder.initial= -Dcom.sun.jmx.mbeanserver.MBeanServer=
    depends_on:
      - db

  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=confluence
      - POSTGRES_PASSWORD=jellyfish
      - POSTGRES_DB=confluencedb
    volumes:
      - confluence-postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5051:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - db
    volumes:
      - confluence-pgadmin-data:/var/lib/pgadmin

  nginx:
    build: ./nginx
    ports:
      - "8090:8090"
      - "8443:8443"
    depends_on:
      - confluence

volumes:
  confluence-data:
  confluence-logs:
  confluence-postgres-data:
  confluence-pgadmin-data: